version: "3.3"

# For local development, only database is running
#
# docker-compose up -d
# uvicorn app.main:app --reload
# for administrate DB you can use PGADMIN uncomment code to section services
# for test you can uncomment test DB section


services:
  default_database:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - ./default_database_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "${DEFAULT_DATABASE_PORT}:5432"
#    networks:
#      network:
#        ipv4_address: 172.18.0.5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    volumes:
      - ./pgadmin_data/:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: unless-stopped
#    ports:
#      - "${DEFAULT_DATABASE_PORT}:5432"
#    networks:
#      network:
#        ipv4_address: 172.18.0.4

#  test_database:
#    restart: unless-stopped
#    image: postgres:latest
#    volumes:
#      - ./test_database_data/db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=${TEST_DATABASE_DB}
#      - POSTGRES_USER=${TEST_DATABASE_USER}
#      - POSTGRES_PASSWORD=${TEST_DATABASE_PASSWORD}
#    env_file:
#      - .env
#    ports:
#      - "${TEST_DATABASE_PORT}:5432"

################################
#####
################################
#  web:
#    container_name: backend
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 172.18.0.3 --port 80 --reload"
#    volumes:
#      - .:/build
#    ports:
#      - "8001:80"
#    restart: always
##    depends_on:
##      - default_database
#    networks:
#      network:
#        ipv4_address: 172.18.0.3
#################################
######
#################################
#  frontend:
#    container_name: frontend
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    environment:
#      - VITE_API_URL="https://api.elbrus.skroy.ru"
#    ports:
#      - "8000:80"
#    restart: always
#    depends_on:
##      - default_database
#      - web
#    networks:
#      network:
#        ipv4_address: 172.18.0.2
#################################
######
#################################
#networks:
#  network:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.18.0.1/16
#          gateway: 172.18.0.1
