"""Init DB

Revision ID: 83598d4afaab
Revises: 
Create Date: 2023-07-06 17:46:07.777493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83598d4afaab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=254), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('company_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('company_name', sa.String(length=254), nullable=True),
    sa.Column('positions', sa.SMALLINT(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('full_description', sa.Text(), nullable=True),
    sa.Column('profession_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('salary_from', sa.Float(), nullable=True),
    sa.Column('salary_to', sa.Float(), nullable=True),
    sa.Column('contact_name', sa.String(length=150), nullable=True),
    sa.Column('contact_company', sa.String(length=150), nullable=True),
    sa.Column('contact_position', sa.String(length=150), nullable=True),
    sa.Column('contacts', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('pic_main', sa.String(), nullable=True),
    sa.Column('pic_main_dm', sa.String(), nullable=True),
    sa.Column('pic_recs', sa.String(), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('team_ids', postgresql.ARRAY(postgresql.UUID(as_uuid=True)), server_default='{}', nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gp_project_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('gp_company_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('gp_user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancy_response',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('gp_project_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('gp_company_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('gp_user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('vacancy_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('data_response', sa.JSON(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancy_skill',
    sa.Column('vacancy_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('skill_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('skill_description', sa.String(length=150), nullable=True),
    sa.Column('is_competence', sa.Boolean(), nullable=True),
    sa.Column('desirability', sa.Enum('REQUIRED', 'DESIRED', 'EMPTY', name='skilldesirability'), nullable=True),
    sa.Column('level', sa.Enum('EMPTY', 'INTERN', 'JUNIOR', 'MIDDLE', 'SENIOR', 'EXPERT', name='skilllevel'), nullable=True),
    sa.Column('priority', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancy.id'], ),
    sa.PrimaryKeyConstraint('vacancy_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancy_skill')
    op.drop_table('vacancy_response')
    op.drop_table('vacancy')
    # ### end Alembic commands ###
